### ISSUE TITLE
How to setup the database

### ISSUE THREAD

**Issue by Shikhar009** [SongoMen/Trader24#5]
Hi, Can you help me setup the database on firestore? I have replaced the credentials with my firebase/firestore credentials but nothing is working beyond sign up. (things like search etc too are not working)

**Comment by SongoMen** [comment]
Stocks on page are fetched from https://iexcloud.io/ . You dont need to set up firebase, it's only gonna save user's portfolio, funds etc. You need to get api key from iexcloud and place it in .env file (there are 2 variables but you can have one key and just place it in both of this variables).

**Comment by Shikhar009** [comment]
Thanks for you reply and regret my issue which got resolved after i updated a key value which got wrongly copied.

Can you just help with the website from where you are using the icons from, I haven't been able to find the right svg for icons

**Comment by SongoMen** [comment]
This is the website i am using https://feathericons.com/

**Comment by Shikhar009** [comment]
Thanks a lot
